replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

postgresql:
  postgresDatabase: voting
  postgresUsername: postgres
  postgresPassword: postgres

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: false 