apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    app: {{ include "voting-backend.name" . }} 