replicaCount: 2
image:
  repository: your-dockerhub-username/voting-backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3001
env:
  - name: DB_HOST
    value: voting-database
  - name: DB_USER
    value: postgres
  - name: DB_PASSWORD
    value: postgres
  - name: DB_NAME
    value: voting
  - name: DB_PORT
    value: "5432" 