apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-database.fullname" . }}
  labels:
    app: {{ include "voting-database.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "voting-database.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "voting-database.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }} 