apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-database.fullname" . }}
  labels:
    app: {{ include "voting-database.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting-database.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUsername }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting-database.fullname" . }}
                  key: postgresql-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          emptyDir: {}
        - name: init-script
          configMap:
            name: {{ include "voting-database.fullname" . }}-init 