apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-database.fullname" . }}
  labels:
    {{- include "voting-database.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresPassword | b64enc }} 