apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-database.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "voting-database.name" . }} 