apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-database.fullname" . }}
  labels:
    app: {{ include "voting-database.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/instance: voting-database
    app.kubernetes.io/name: voting-database 