name: Deploy Voting App to GKE

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GCR_REGION: gcr.io
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - Print SHA
        run: echo "Current commit SHA: ${{ github.sha }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker $GCR_REGION

      - name: Build and push frontend Docker image
        run: |
          docker build -t $GCR_REGION/$PROJECT_ID/voting-frontend:$IMAGE_TAG ./apps/frontend
          docker push $GCR_REGION/$PROJECT_ID/voting-frontend:$IMAGE_TAG

      - name: Build and push backend Docker image
        run: |
          docker build -t $GCR_REGION/$PROJECT_ID/voting-backend:$IMAGE_TAG ./apps/backend
          docker push $GCR_REGION/$PROJECT_ID/voting-backend:$IMAGE_TAG

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy with Helm
        run: |
          helm upgrade --install voting-database ./charts/database
          helm upgrade --install voting-backend ./charts/backend --set image.repository=$GCR_REGION/$PROJECT_ID/voting-backend,image.tag=$IMAGE_TAG
          helm upgrade --install voting-frontend ./charts/frontend --set image.repository=$GCR_REGION/$PROJECT_ID/voting-frontend,image.tag=$IMAGE_TAG 