name: Deploy Voting App to GKE

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}
      GCR_REGION: gcr.io
      IMAGE_TAG: latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "$(gcloud --version)"

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker $GCR_REGION

      - name: Build and push frontend Docker image
        run: |
          docker build -t $GCR_REGION/$PROJECT_ID/voting-frontend:$IMAGE_TAG ./apps/frontend
          docker push $GCR_REGION/$PROJECT_ID/voting-frontend:$IMAGE_TAG

      - name: Build and push backend Docker image
        run: |
          docker build -t $GCR_REGION/$PROJECT_ID/voting-backend:$IMAGE_TAG ./apps/backend
          docker push $GCR_REGION/$PROJECT_ID/voting-backend:$IMAGE_TAG

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
          kubectl config current-context

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version

      - name: Deploy with Helm
        run: |
          helm upgrade --install voting-database ./charts/database --recreate-pods
          helm upgrade --install voting-backend ./charts/backend --set image.repository=$GCR_REGION/$PROJECT_ID/voting-backend,image.tag=$IMAGE_TAG --recreate-pods
          helm upgrade --install voting-frontend ./charts/frontend --set image.repository=$GCR_REGION/$PROJECT_ID/voting-frontend,image.tag=$IMAGE_TAG --recreate-pods